# Generated by Django 5.2.6 on 2025-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0002_employee_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='permanent_same_as_present',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
