# Generated by Django 5.2.6 on 2025-10-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0004_employee_created_at_employee_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='employee',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='year_of_completion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
