# Generated by Django 5.2.6 on 2025-10-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0006_employee_company_employee_currently_work_here_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='highest_qualification',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='offer_letter',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skill_set',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='source_of_hire',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tentative_joining_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
    ]
