# Generated by Django 5.2.6 on 2025-10-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0007_remove_employee_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='source_of_hire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
