# Generated by Django 5.2.6 on 2025-10-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0009_employee_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_salary',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
