# Generated by Django 5.2.6 on 2025-10-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0010_alter_employee_current_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
