# Generated by Django 5.2.6 on 2025-10-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0011_alter_employee_current_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='check_in_status',
            field=models.BooleanField(default=False),
        ),
    ]
