# Generated by Django 5.2.6 on 2025-10-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0012_employee_check_in_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Administration', 'Administration'), ('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Team Member', 'Team Member')], default='Team Member', max_length=50),
        ),
    ]
