# Generated by Django 5.2.6 on 2025-10-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0013_alter_employee_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Administration', 'Administration'), ('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Team Member', 'Team Member')], default='Team Member', max_length=50, null=True),
        ),
    ]
