# Generated by Django 5.2.6 on 2025-10-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0016_alter_employee_last_name_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
