# Generated by Django 5.2.6 on 2025-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0017_attendance_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='eight_hours_completed',
            field=models.BooleanField(default=False),
        ),
    ]
