# Generated by Django 5.2.6 on 2025-11-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0018_attendance_eight_hours_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
