# Generated by Django 5.2.6 on 2025-11-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_portal", "0019_holiday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CEO", "CEO"),
                    ("Administration", "Administration"),
                    ("Manager", "Manager"),
                    ("Assistant Manager", "Assistant Manager"),
                    ("Team Member", "Team Member"),
                ],
                default="Team Member",
                max_length=50,
                null=True,
            ),
        ),
    ]
