# Generated by Django 5.2.6 on 2025-11-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0022_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
