# Generated by Django 5.2.7 on 2025-11-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_portal", "0024_designation_alter_employee_title"),
    ]

    operations = []
