# Generated by Django 5.2.7 on 2025-11-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0025_add_title_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Administration', 'Administration'), ('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Team Member', 'Team Member')], default='Team Member', max_length=50, null=True),
        ),
    ]
