# Generated by Django 5.2.6 on 2025-12-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0026_alter_employee_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
