# Generated by Django 5.2.7 on 2025-12-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0029_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
