# Generated by Django 5.2.6 on 2025-12-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0031_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Administration', 'Administration'), ('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Team Member', 'Team Member'), ('Managing Director', 'Managing Director'), ('Chief Executive Officer', 'Chief Executive Officer'), ('Software Engineer', 'Software Engineer'), ('Web Developer', 'Web Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Team Lead', 'Team Lead'), ('Technical Lead', 'Technical Lead'), ('Senior Manager', 'Senior Manager'), ('Consultant', 'Consultant'), ('Junior Developer', 'Junior Developer'), ('Trainee', 'Trainee'), ('Intern', 'Intern')], default='Team Member', max_length=50, null=True),
        ),
    ]
