# Generated by Django 5.2.7 on 2025-12-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0034_leave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
