# Generated by Django 5.2.6 on 2025-12-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0036_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
